### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by jman13378** [dylwedma11748/patreon-java-v2#1]
When do you expect this to be ready for personal/commercial use as the patreon api isnt maintained

**Comment by dylwedma11748** [comment]
Once I'm finished with the resource classes and testing out if they work. It's getting pretty close to being ready, but I can't give an exact date.

**Comment by dylwedma11748** [comment]
The library has been released to JitPack and it is confirmed to be working. Refer to the README for instructions on importing it.
